sudo: required
dist: xenial
language: go
go: "1.10"

branches:
  only:
  - master

addons:
  apt:
    packages:
    - libvirt-bin
    - qemu-kvm

jobs:
  include:
  - stage: Functional test
    name: Test kubevirt-cpu-nfd-plugin 
    before_script: 
      - locate cpu_map
      - ls -l /usr/share/libvirt/cpu_map/
      - sudo mkdir -p "/etc/kubernetes/node-feature-discovery/source.d/";
      - sudo cp test/virsh-domcapabilities-example.xml /etc/kubernetes/node-feature-discovery/source.d/virsh-domcapabilities.xml
      - make image;

    script: bash -x automation/functional_test.sh
    deploy:
      before_script: 
      - echo "$NFDPASS" | docker login -u="$NFDNAME" quay.io --password-stdin
      provider: script
      skip_cleanup: true
      script: make push-image
      on:
        branch: master
        tags: true

